In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

import warnings
warnings.filterwarnings('ignore')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [42]:
df= pd.read_json("hotelreview.json")

In [43]:
df.head()

,Name,Ratings,xRkPPb,Review,Hotel Reply
0,Anish Parikh,4/5,3 months ago on \nGoogle,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you..."
1,Javeria Shaikh,4/5,a month ago on \nGoogle,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...
2,Dhaval Ahir,1/5,a month ago on \nGoogle,"Worst service experience at Miramar Hotel, Dam...",NaN
3,Kamlesh Pal,4/5,a month ago on \nGoogle,Had a great experience at the PhonePe event he...,NaN
4,Dhruvanshu Pitroda,1/5,2 weeks ago on \nGoogle,Extremely unprofessional behavior from the man...,NaN

In [44]:
df.shape

(1600, 5)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         1599 non-null   object
 1   Ratings      1600 non-null   object
 2   xRkPPb       1600 non-null   object
 3   Review       1600 non-null   object
 4   Hotel Reply  201 non-null    object
dtypes: object(5)
memory usage: 62.6+ KB

In [46]:
df.Review.value_counts().shape

(1591,)

In [47]:
df.Ratings.value_counts()

Ratings
5/5    633
4/5    436
1/5    235
3/5    203
2/5     93
Name: count, dtype: int64

In [48]:
df.isna().sum()

Name              1
Ratings           0
xRkPPb            0
Review            0
Hotel Reply    1399
dtype: int64

In [49]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [50]:
len(stopwords.words('english'))

198

In [51]:
import re
import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,1600):
    review = re.sub('[^a-zA-Z]',' ',df['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ ps.stem(word) for word in review if not word in stopwords.words('english') ]
    review = ' '.join(review)
    print(review)
    corpus.append(review)

visit hotel miramar last week dinner realli enjoy experi place love beachsid seat area relax vibe perfect
hotel miramar hotel restuar live orchestra weekend restaur right across coast scenic morn well
worst servic experi miramar hotel daman one disappoint hotel stay pm hotel
great experi phonep event held miramar hotel food servic excel staff support well manag overal arrang smooth truli appreci hospit coordin miramar hotel team
extrem unprofession behavior manag repeatedli told eat fast stop talk disturb hotel charg servic tax plate rice treat guest like nuisanc unaccept
everyth good hotel except price food bar idea charg high averag indian restur price half compar hotel rest complaint anyth els weekend gateway perfect
went famili experi terribl manag continu disturb us dinner forc us order fast high price kind servic complet overr place
good hotel issu beach watch use complet muddi stoni offshor area
restaur insid hotel miramar lot go food price major letdown order fish finger price good fruit punch also quit underwhelm experi
manag extrem rude dinner told hotel close forc order fast even allow eat properli complet ruin experi worst manag zero hospit
need learn cook food ask servic worst expect liter order give even dene
price bit high live music singer bad felt like loud noic sooth music servic also slow
nice place food drink fantast place sea view hear full velu servic food definit memoris place love place seat area ssite seen attach number one famili food place enjoy place best experi
thank manag process cancel book cancel due person issu show hotel profession manag custom focus definit book hotel whenev plan visit daman next tamaro khub aabhar
extrem disappoint experi hotel miramar food overpr tasteless serv small portion compar high rate charg
avoid place cost order chicken lollipop chicken tandoori disast chicken lollipop raw chicken tandoori tasteless make matter wors got sick night
recommend restaur food qualiti poor compar price
worst food worst servic staff ate plate serv prove right mr arvind manag sens hospit done food bad price high make sens
help amaz staff liter say anyth give hand servic smooth hassl free check experi humbl cheer front desk staff
great room great restaur great ambienc life music complet packag thank miramar
reastaur locat side sea view amaz even food also decent love atmospher sround
food realli amaz cooper staff especi miss rina maam miss kalpna miss puja nice hospit
best hotel town sinc amaz food luxuri stay top notch servic come year
one best place stay daman locat adjac sea awesom sea view room spaciou bathroom well maintain swim pool facil good
absolut wonder stay amaz experi hotel staff warm welcom room spotless comfort locat perfect close
miss puja serv well great experi hae good food cleanli well bheva staff good properti
mayb improv veg food charg much food good
neat clean hotel good servic everyth avail
provid atleast pic litr water two peopl instead gave piec ml
great experi stay first time great servic room thing good
excel place daman one go place daman excel food polit staff clean reson size room good restaur ambienc problem small park space velet park avail food
great time hotel miramar sea face restaur main highlight hotel along superb food room servic prompt courteou
hotel miramar daman wonder experi recent visit hotel miramar daman event newli built banquet
nice experi staff good behaviour nice locat font devika beach
delight stay experi hotel truli memor ambianc seren servic impecc everi detail thought curat perfect blend comfort eleg highli recommend relax getaway
truli divin stay moment arriv embrac warmth seren ambianc exud eleg servic flawless everi detail spoke comfort care heavenli retreat truli sanctuari soul highli recommend
visit miramar daman recent locat ambianc decent overal experi averag food okay noth particularli memor bad either
staff rude courteou food drink ridicul expens
best food best locat best hospit satisfi
worst servic ever seen order food drink take minimum minut serv tabl ask waiter order never came back said minut gone
face lot chalang book room send pic room time check theri offer anoth room grade somani argument given room shown
wonder experi hotel miramar staff friendli profession room spotless comfort locat perfect everyth check check seamless highli recommend relax hassl free stay
best servic also recept banquet staff good corpor best stay
good experi miramar staff friendli natur night dinner awesom
nice dine tasti food near costl highway
visit hotel weekend experi expect charg high compar facil provid basic amen like tea kettl water bottl glass avail upon request
alway fun great locat staff alway welcom smile
miramar year back n revisit yesterday lost glori ambienc sinc orchestra still restrict small space noisi food good doubt
cozi place holiday good food facil friendli staff
good food especi non veg lover would love option meat fish vegetarian option also good everyth tast yummi best part maintain qualiti food sinc year locat place opposit sea near devka beach best seller vibe ambienc love
recent visit hotel miramar restaur daman order veg fri rice veg soup unfortun food mark qualiti poor definit worth high price quit disappoint
great view arbian sea coast cozi room almost perfect servic
great view good ambianc good servic visit view sure visit sure
amaz room beach side view deck pleasant stay
horribl stay miramar huge ripoff room bad view book expens room k given room face road upon request room chang show room ground floor face
love hotel excel spaciou room would definit recommend
room size good hotel staff servic avarag locat near beach get beach view banquet hall
room clean comfort size room also good annual event compani kind arrang made awesom food great problem mosquito room fix problem neg
best room duplex delux must tri room enjoy tooo much famili
worst servic beyond imagin pay hefti money room welcom staff extrem rude expect servic big name experi miramar daman locat room realli good
good servic bad visit futur
good locat beach gd place walk morn even good beach road
pathet food servic insan expens
miramar wonder beachsid restaur fantast view sea make excel spot relax meal ambianc truli special especi love dine direct sea view tabl food
good hotelmiramar hotel miramar lot problem hotel know room chang took room rs room servic good manag good dinner rate high qualiti good
good food enjoy atmospher
lot loveabl nice experi
good servic staff good food good swming poor good locat bark fastest vari good satr lakh star
one luxuri hotel daman amaz decor view locat superb servic earth friendli courteou peopl
stay miramar hotel daman suit room th june mother celebr birthday unfortun special weekend turn nightmar
well hospit awesom servic
one worst experi staff rude dont fridg room serv ice room illeg thing insid take permiss god know mani peopl
hotel miramar best hotel daman never go wrong choos stay miramar room food ambienc everyth perfect
recent stay hotel miramar daman room clean neat well maintain room servic quit good ad comfort experi howev found food especi lunch dinner highli expens
second home week felt like home great facil excel servic profession staff highli recommend thank
went marin mood restaur tawa prawn starter amaz found everyth bit averag howev realli cordial nice server explain menu patient us
even start worth even support see bank offic transit id statement pay payment mode tri call one bank form side made call bank
everyth good even staff sweet help
great stay hotel miramar daman great servic great food hospit great
great food drink gopal great help
nice view sea restaur
good servic team gopal da ji pooja
good hotel stay daman locat excel minimum distrub hotel side hygien standard good thing improv like car pull servic ad bit improv requir morn breakfast special jain peopl
good atmospher good food tast
great place stay nice room well manag food great
recent stay hotel miramar daman pleasant experi beachfront locat devka beach perfect relax room clean spaciou comfort though pool well maintain food restaur realli good overal great spot relax beachsid getaway
awesom hotel miramar resort interior best room servic food yummi breakfast dinner resort hotel quit peac relax
doubl room good central ac key card lock work end day staff use key unlock door central ac room servic pretti good swim pool clean food expens howev good qualiti well prepar serv
properti recept staff special mr shri ms soni kind help room neat clean food qualiti excel sea view restaur servic realli good realli enjoy stay definit come back
good time wonder experi
overal love stay miramar excel properti good ambienc good servic
moment arriv felt welcom care room spaciou clean amen need fantast beauti host care help room clean breakfast wonder thankyou
room smoke room stale cigarett odour remain stay room cushion upholsteri cigarett burnt hole separ bathroom toilet made without proper layout bathroom tap one corner difficult use chair work tabl provid
good food pujabi option thank much nice servic puspanjali
good hospit delici food well maintain pool
best staff excel servic aman singh
restraunt food servic poor
hotel mira mar daman offer solid stay central locat make easi explor local attract room clean well maintain though area could use updat staff note friendli help attitud good choic seek comfort frill experi
servic behavior staff absolut aw wors recommend anyon stay properti
overal stay miramar hotel daman enjoy hotel boast good restaur though room improv swim pool pleasant could benefit shade area room comfort although certain
overpr food beverag averag food qualiti definit need improv
recent visit experi extrem good nice comfort room thay serv good qualiti varieti food an realli love enjoy qualiti time one attract point enjoy beach look
locat prime area hotel offer multipl stay dine option option duplex room provid ampl space comfort hotel consid best daman unfortun longer recommend famili stay may still food option group friend
food expens less quantiti
review long due stay hotel multipl time kid ninte great memori mid decid visit friend night room clean spaciou swim pool
realli good experi good hospit food servic well thank miramar
food good tri
great food room entertain
scam total bill scam custom enjoy live show platform think custom drunk count drink food order staff sharp mind keep
properti best view restaur room excel howev food averag extrem costli imagin pay rs mix fri rice tea rs servic restaur pathet realli
refriger hot water kettl mani hotel allow outsid drink still refriger charg good amount give basic thing order ice bag mention cost rs like even like tast food per price
great food stay hospit
nice servic good room food
best hotel inchant view room even sit enjoy food front seashor late night food avail servic
room spaciou comfi servic good overal vibe space give posit food tasti lift majorli improv properti lift quit old full mosquito
worst food qualiti food servic improv price high given food qualiti chang staff rude incorpor hidden charg expect pay custom
nice n peac experi
realli great experi breakfast view realli great full sea view enjoy breakfast
rate restaur miramar base pro con pro
delici food good servic slightli costli option locat view cost much
good ambienc good food
first order quick minut sit singl waiter came tabl ask need anyth saw tabl waiter attend tabl singl waiter bad one beer left never ever go come back place
pathet food expenc locat good servic good recommend food lover
restur charg star hotel mumbai pint beer cost us
amaz view great servic love staff food utterli delici come back sure
love resort beach view beach much clean view awesom place bar great place relax beer take view
beach uper resort avelo e nice locat staff servic staff behavior also good food also good excel
gopal restaur guy given good servic
write review sit restaur parti order drink starter waiter taken away menu time everytim come tabl take away menu yet order
visit friend famili vacat room okay certain price given room relat servic slow respond got one room check hour later gave smoke room time odour cigarett room
hotel good locat easi access sea face room spaciou tast decor room servic quit disappoint overal bit pricey moder experi
went saturday even dinner staff rude ignor food overpr quantiti justifi price chicken chilli piec capsicum rs
nice hotel good delici food ever find daman real test good enough room qualiti also high qualiti decor nit clean facil get
delux room good book suit howev chang see suit open restaur great locat devka beach food good though littl expens side recept staff courteou effici overal nice experi
love place amaz ambienc luxuri room delici food staff friendli visit properti year properti perfect vacat destin wed
hotel miramar devka beach daman known conveni locat decent amen provid easi access beach nearbi attract beach mix review devka beach often describ rocki
wish could give star place visit sinc childhood recent visit shatter memori servic pathet restaur sit weird mean ur almost balconi
nice place stay famili room nice clean well maintain food also good
well place hotel decent food sanit lobbi decent buffet howev take time deliv food tabl menu item overli price lunch might cost thousand vicin sea shore make picturesqu mind delay food deliveri
properti good stay best room view amaz give hotel servic properti could better maintain anyon go daman recommend take best room possibl
room smell dirti bedsheet pillow smelli washroom yaaakkk
good hospit food thank staff discov perfect getaway miramar resort daman enjoy luxuri accommod stun sea view fine dine relax atmospher ideal memor escap regard
stay newli construct expans miramar hotel amen excel problem swim pool side cross road reach part hotel use swim pool get view sea new part
costli like loot food tasti price like accord name simpl thumb bottom market rs hotel doubl price bad
last weekend decid lunch hotel miramar daman visit place last year good experi decid visit
rate suitabl per servic qualiti food differenti among custom ask pass discount overal good one
hotel look great outsid interior room par speciou neat clean room
well maintain properti daman staff servic food excel mainli gm mr jitenterji gem person told gave excel behaviour thankyou kind gestur support
review miramar restaur terribl experi came lunch end leav
locat awesom given room new properti opposit main build new clean tidi good properti nice pool
good locat bang beach larg airi room facil ok food qualiti good restaur recent demolit carri beach face part properti debri remov open
pathet experi wast entir money charg like star servic like star sever cockroach whole night room wifi deni tell capac
got good restaur differ level bar live music good food hotel design sea view room rate averag around rs delux room food alcohol price bit higher side well train staff also serv hooka along drink
smelli restaur unskil staff worst servic experienc hotel definit come back
stay decent compris swim pool best thing enjoy picturesqu view sea food provid quit expens expect tourist destin otherwis mani food
near farsid locat worthi tetotel per experi room servic room best daman
restaur experi good consid overpr menu subpar food order tandoori chicken starter cook
stay hotel one night oct check check hassel free smooth howev suggest put one staff faster check process rush guest check cleanli hotel
went properti dinner servic sooo slow decid leav one starter btw great post ask bill almost time differ peopl end get
heard lot place henc visit big point daman check list
miramar brand daman devka expect high book hotel stay first time book miramar form countless visit daman devka
wed function may disturb
one promin hotel resort daman miramar locat main road one great view beach room hotel fairli new room reason small direct access
room old build face sea face need renov
miramar great expens option hotel restaur room good locat great food ok live orchestra everi even dine cover charg bit overr experi valu money
sea side restaur year though miss fencesid sea food still amz made decent arrang sea side dine balconi one excel seem govt project commpel modifi arrang place worth appreci
went th june colleagu first hand menu despit request time mind place crowd half waiter manag interest
worst tast servic expens everi dish minimum one singl dish gravi
great place visit much visit breakfast hotel beauti view sea morn
small thing done make much better poor room servic
good clean spaciou room nice clean swim pool massag steam bath option locat prime place lot shop restaur around servic food danc floor also key highlight weekend place
friend wed day properti nice clean also well maintain servic nice locat beach beach lover would love stay restaur food also good
restaur food qualiti poor minestron soup sour dri manchurian stale tissu stink dal rice tasteless experi bad
amaz venu destin wed holiday visit stay brunch lunch enjoy even coffe sea sight breezi sunset view food good
live band decent extrem loud even first floor imposs speak next person singer terribl made feel mistak go place
great locat best room pent hous hardli avail reason room like hotel would recommend presidenti suit room privaci balconi end restaur start
fraud fraud fraud call hotel tell gie room reach discuss book told give
hotel situat besid sea room face toward sea restaur face sea dine experi awesom weekday weekend live orchestra go
feedback fridg place keep cloth
organ confer staff help includ hotel manag happi hall arrang well food arrang budget realli happi recommend zenith hall funtion sure visit soon
stay last night overal experi miramar good littl higher price room renov good ambienc relax
one worst hotel manag stay rd june recept guy offer discount f b sell room get bill deni start fight guest mani guest faceinh issu
find hotel well locat beach view beach room room plan well kept mark food good servic also good best part restor beach
miramar great loction expens option hotel restaur room nice locat great food ok live orchestra everi even dine cover charg costli restaur hotel
hotel locat prime area daman e devka beach road view hotel toward sea realli nice
subroto manag worst regular last year deni dine nd floor subroto alway use later even deni discount regular last time dine miramar take
good hotel costli one good food servic littl slow good live orchestra pm also huge place back yard hotel sit enjoy live music friend park space also good hotel park keep car safe
food qualiti averag accord price restaur charg servic also par waiter even respond accord requir ask time bottl miner water
came valentin day expect opposit order macroni good later pizza base thick raw veg chees sandwich worth better eat outsid stall atleast food tasti peopl charg serv less pleas avoid go
room worst charg k provid refriger ac work realli bad order ice cube room charg k also charg swim costum charg locat good servic facil worst
nice hotel situat main road devka beach also face sea side pleasant getaway peopl look qualiti time famili friend weekend tast veg food tasti popular resort anyon plan go book quit advanc
visit offic confer coupl day stay room
attend cousin wed miramar room clean well maintain suit great fantast view sea pool clean staff courteou help lawn great huge wed food delici
disappoint experi restaur food lack qualiti price unreason high addit infrastructur seem outdat worth cost overal worthi dine choic consid subpar offer high expens
mr amit staff vari co opr fodd excel terma qualiti quantiti
room upgrad els everyth good
great hotel near devka beach happi servic staff help good food drink option pool massag steam sauna facil buffet breakfast also good good wifi internet room neat tidi room
starter till pm gather peopl name fruit counter papita tarbuz kharbuza angur welcom drink artifici real bottl rude behaviour guest
one best hotel stay daman

In [52]:
# After building corpus
df['Cleaned_Review'] = corpus

In [53]:
df.head()

,Name,Ratings,xRkPPb,Review,Hotel Reply,Cleaned_Review
0,Anish Parikh,4/5,3 months ago on \nGoogle,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you...",visit hotel miramar last week dinner realli en...
1,Javeria Shaikh,4/5,a month ago on \nGoogle,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...,hotel miramar hotel restuar live orchestra wee...
2,Dhaval Ahir,1/5,a month ago on \nGoogle,"Worst service experience at Miramar Hotel, Dam...",NaN,worst servic experi miramar hotel daman one di...
3,Kamlesh Pal,4/5,a month ago on \nGoogle,Had a great experience at the PhonePe event he...,NaN,great experi phonep event held miramar hotel f...
4,Dhruvanshu Pitroda,1/5,2 weeks ago on \nGoogle,Extremely unprofessional behavior from the man...,NaN,extrem unprofession behavior manag repeatedli ...

In [54]:
df.isnull().sum()

Name                 1
Ratings              0
xRkPPb               0
Review               0
Hotel Reply       1399
Cleaned_Review       0
dtype: int64

In [55]:
import pandas as pd

# Example: mapping ratings to sentiment
def get_sentiment(rating_str):
    # Extract numeric rating (e.g., "4/5" → 4)
    try:
        rating = int(rating_str.split('/')[0])
    except:
        return "Neutral"
    
    if rating >= 4:
        return "Positive"
    elif rating <= 2:
        return "Negative"
    else:
        return "Neutral"

# Apply function to Ratings column
df['Sentiment'] = df['Ratings'].apply(get_sentiment)
df.head()

,Name,Ratings,xRkPPb,Review,Hotel Reply,Cleaned_Review,Sentiment
0,Anish Parikh,4/5,3 months ago on \nGoogle,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you...",visit hotel miramar last week dinner realli en...,Positive
1,Javeria Shaikh,4/5,a month ago on \nGoogle,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...,hotel miramar hotel restuar live orchestra wee...,Positive
2,Dhaval Ahir,1/5,a month ago on \nGoogle,"Worst service experience at Miramar Hotel, Dam...",NaN,worst servic experi miramar hotel daman one di...,Negative
3,Kamlesh Pal,4/5,a month ago on \nGoogle,Had a great experience at the PhonePe event he...,NaN,great experi phonep event held miramar hotel f...,Positive
4,Dhruvanshu Pitroda,1/5,2 weeks ago on \nGoogle,Extremely unprofessional behavior from the man...,NaN,extrem unprofession behavior manag repeatedli ...,Negative

In [56]:
df.Sentiment.value_counts()

Sentiment
Positive    1069
Negative     328
Neutral      203
Name: count, dtype: int64

In [57]:
df['Ratings'].unique()

array(['4/5', '1/5', '5/5', '3/5', '2/5'], dtype=object)

In [58]:
# Define mapping dictionary
rating_map = {
    '4/5': 4,
    '1/5': 1,
    '5/5': 5,
    '3/5': 3,
    '2/5': 2
}

# Replace values in Ratings column
df['Ratings'] = df['Ratings'].map(rating_map)

print(df['Ratings'].unique())

[4 1 5 3 2]

In [59]:
df.head()

,Name,Ratings,xRkPPb,Review,Hotel Reply,Cleaned_Review,Sentiment
0,Anish Parikh,4,3 months ago on \nGoogle,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you...",visit hotel miramar last week dinner realli en...,Positive
1,Javeria Shaikh,4,a month ago on \nGoogle,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...,hotel miramar hotel restuar live orchestra wee...,Positive
2,Dhaval Ahir,1,a month ago on \nGoogle,"Worst service experience at Miramar Hotel, Dam...",NaN,worst servic experi miramar hotel daman one di...,Negative
3,Kamlesh Pal,4,a month ago on \nGoogle,Had a great experience at the PhonePe event he...,NaN,great experi phonep event held miramar hotel f...,Positive
4,Dhruvanshu Pitroda,1,2 weeks ago on \nGoogle,Extremely unprofessional behavior from the man...,NaN,extrem unprofession behavior manag repeatedli ...,Negative

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            1599 non-null   object
 1   Ratings         1600 non-null   int64
 2   xRkPPb          1600 non-null   object
 3   Review          1600 non-null   object
 4   Hotel Reply     201 non-null    object
 5   Cleaned_Review  1600 non-null   object
 6   Sentiment       1600 non-null   object
dtypes: int64(1), object(6)
memory usage: 87.6+ KB

In [61]:
df.isnull().sum()

Name                 1
Ratings              0
xRkPPb               0
Review               0
Hotel Reply       1399
Cleaned_Review       0
Sentiment            0
dtype: int64

In [62]:
import pandas as pd

# Step 1: Drop rows where Name is null
df = df.dropna(subset=['Name'])

In [63]:
df.head()

,Name,Ratings,xRkPPb,Review,Hotel Reply,Cleaned_Review,Sentiment
0,Anish Parikh,4,3 months ago on \nGoogle,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you...",visit hotel miramar last week dinner realli en...,Positive
1,Javeria Shaikh,4,a month ago on \nGoogle,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...,hotel miramar hotel restuar live orchestra wee...,Positive
2,Dhaval Ahir,1,a month ago on \nGoogle,"Worst service experience at Miramar Hotel, Dam...",NaN,worst servic experi miramar hotel daman one di...,Negative
3,Kamlesh Pal,4,a month ago on \nGoogle,Had a great experience at the PhonePe event he...,NaN,great experi phonep event held miramar hotel f...,Positive
4,Dhruvanshu Pitroda,1,2 weeks ago on \nGoogle,Extremely unprofessional behavior from the man...,NaN,extrem unprofession behavior manag repeatedli ...,Negative

In [64]:
df.isnull().sum()

Name                 0
Ratings              0
xRkPPb               0
Review               0
Hotel Reply       1398
Cleaned_Review       0
Sentiment            0
dtype: int64

In [65]:
df['Hotel Reply'] = df['Hotel Reply'].fillna('not reply')

In [66]:
df.isnull().sum()

Name              0
Ratings           0
xRkPPb            0
Review            0
Hotel Reply       0
Cleaned_Review    0
Sentiment         0
dtype: int64

In [67]:
# Create HotelReplyStatus column
df['HotelReplyStatus'] = df['Hotel Reply'].apply(lambda x: 0 if x == 'not reply' else 1)

In [68]:
df.isnull().sum()

Name                0
Ratings             0
xRkPPb              0
Review              0
Hotel Reply         0
Cleaned_Review      0
Sentiment           0
HotelReplyStatus    0
dtype: int64

In [69]:
df = df.drop("xRkPPb", axis=1)

In [70]:
df.head()

,Name,Ratings,Review,Hotel Reply,Cleaned_Review,Sentiment,HotelReplyStatus
0,Anish Parikh,4,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you...",visit hotel miramar last week dinner realli en...,Positive,1
1,Javeria Shaikh,4,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...,hotel miramar hotel restuar live orchestra wee...,Positive,1
2,Dhaval Ahir,1,"Worst service experience at Miramar Hotel, Dam...",not reply,worst servic experi miramar hotel daman one di...,Negative,0
3,Kamlesh Pal,4,Had a great experience at the PhonePe event he...,not reply,great experi phonep event held miramar hotel f...,Positive,0
4,Dhruvanshu Pitroda,1,Extremely unprofessional behavior from the man...,not reply,extrem unprofession behavior manag repeatedli ...,Negative,0

In [72]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['Review'])

# Step 2: Topic modeling with LDA
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(X)

# Step 3: Get top words per topic
terms = vectorizer.get_feature_names_out()
topic_keywords = {}
for idx, topic in enumerate(lda.components_):
    top_terms = [terms[i] for i in topic.argsort()[-5:]]
    topic_keywords[idx] = top_terms
    print(f"Topic {idx}: {top_terms}")

# Step 4: Assign each review to its most likely topic
topic_distribution = lda.transform(X)
df['topic'] = topic_distribution.argmax(axis=1)

# Step 5: Auto-label using top keyword(s) of each topic
df['classification'] = df['topic'].apply(lambda t: " / ".join(topic_keywords[t][:2]))

Topic 0: ['hotel', 'sunday', 'prices', 'staff', 'saturday']
Topic 1: ['place', 'service', 'nice', 'food', 'good']
Topic 2: ['mosquitoes', 'sitting', 'hotel', 'fine', 'rate']
Topic 3: ['loved', 'perfect', 'music', 'place', 'live']
Topic 4: ['luxury', 'best', 'better', 'wonderful', 'lovely']

In [73]:
df.head()

,Name,Ratings,Review,Hotel Reply,Cleaned_Review,Sentiment,HotelReplyStatus,topic,classification
0,Anish Parikh,4,⭐⭐⭐⭐☆\nVisited Hotel Miramar last week for din...,"Dear Guest,\nThank you so much for sharing you...",visit hotel miramar last week dinner realli en...,Positive,1,3,loved / perfect
1,Javeria Shaikh,4,Hotel Miramar is a hotel with restuarant and l...,Thank you for the rating! We're so glad you en...,hotel miramar hotel restuar live orchestra wee...,Positive,1,1,place / service
2,Dhaval Ahir,1,"Worst service experience at Miramar Hotel, Dam...",not reply,worst servic experi miramar hotel daman one di...,Negative,0,1,place / service
3,Kamlesh Pal,4,Had a great experience at the PhonePe event he...,not reply,great experi phonep event held miramar hotel f...,Positive,0,1,place / service
4,Dhruvanshu Pitroda,1,Extremely unprofessional behavior from the man...,not reply,extrem unprofession behavior manag repeatedli ...,Negative,0,2,mosquitoes / sitting

In [71]:
#df.to_csv('hotelreviewanalysis.csv', index=False)